modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/theatricalmod/theatrical-forge/issues"
license="Apache-2.0"
[[mods]]
    modId="theatrical"
    version="${file.jarVersion}"
    displayName="Theatrical"
    credits="Manmaed"
    authors="Rushmead"
    description='''
    '''
